#自定义sftp的配置，需要配置类读取
sftp:
  isUseSftp: 1
  server:
    ip: 192.168.1.10
    port: 22
    username: root
    password: 123
    downloadSleep: 100 #文件下载失败下次超时重试时间
    downloadRetry: 10 #文件下载失败重试次数
    uploadSleep: 100 #文件上传失败下次超时重试时间
    uploadRettry: 10  #文件上传失败重试次数

server:
  port: 8099
